version: '3'
services:
  api-server:
    external_links:
      - goofy_meninsky
    build: .
    restart: always
    ports:
      - "80"
    environment:
      - VIRTUAL_HOST=api.hacktzi.tk
      - PORT=80
