version: '3'
services:
  api-server:
    networks:
      - default
      - my-server_default
    build: .
    restart: always
    ports:
      - "80"
    environment:
      - VIRTUAL_HOST=api.hacktzi.tk
      - PORT=80
networks:
  my-server_default:
    external: true
